#!/bin/bash

curl -o Kconfig https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/Kconfig
curl -o Makefile https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/Makefile
curl -o README https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/README
curl -o fb_agm1264k-fl.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_agm1264k-fl.c
curl -o fb_bd663474.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_bd663474.c
curl -o fb_hx8340bn.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_hx8340bn.c
curl -o fb_hx8347d.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_hx8347d.c
curl -o fb_hx8353d.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_hx8353d.c
curl -o fb_hx8357d.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_hx8357d.c
curl -o fb_hx8357d.h https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_hx8357d.h
curl -o fb_ili9163.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ili9163.c
curl -o fb_ili9320.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ili9320.c
curl -o fb_ili9325.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ili9325.c
curl -o fb_ili9340.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ili9340.c
curl -o fb_ili9341.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ili9341.c
curl -o fb_ili9481.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ili9481.c
curl -o fb_ili9486.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ili9486.c
curl -o fb_pcd8544.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_pcd8544.c
curl -o fb_ra8875.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ra8875.c
curl -o fb_s6d02a1.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_s6d02a1.c
curl -o fb_s6d1121.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_s6d1121.c
curl -o fb_ssd1289.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ssd1289.c
curl -o fb_ssd1305.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ssd1305.c
curl -o fb_ssd1306.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ssd13060.c
curl -o fb_ssd1325.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ssd1325.c
curl -o fb_ssd1331.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ssd1331.c
curl -o fb_ssd1351.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_ssd1351.c
curl -o fb_st7735r.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_st7735r.c
curl -o fb_st7789v.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_st7789v.c
curl -o fb_tinylcd.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_tinylcd.c
curl -o fb_tls8204.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_tls8204.c
curl -o fb_uc1611.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_uc1611.c
curl -o fb_uc1701.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_uc1701.c
curl -o fb_upd161704.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_upd161704.c
curl -o fb_watterott.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fb_watterott.c
curl -o flexfb.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/flexfb.c
curl -o fbtft-bus.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fbtft-bus.c
curl -o fbtft-core.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fbtft-core.c
curl -o fbtft-io.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fbtft-io.c
curl -o fbtft-sysfs.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fbtft-sysfs.c
curl -o fbtft.h https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fbtft.h
curl -o fbtft_device.c https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/fbtft_device.c
curl -o internal.h https://raw.githubusercontent.com/beagleboard/linux/4.1/drivers/staging/fbtft/internal.h
